excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://RTasha.github.io
name: Awesome
description: The best GitHub writing platform
author: Tasha
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 